### ISSUE TITLE
Nothing output when running rqscheduler

### ISSUE THREAD

**Issue by Sshuichi** [ui/rq-scheduler#82] opened 2015-06-11 20:30 UTC
I'm running rqscheduler -v , and ./manage.py rqscheduler -v but nothing is output , no logging no nothing

I'm using the last version when I run it for the second time it says that it's already running.

when I check the current jobs , all of them are enqueued at NONE 

This is my code : `def func(arg1):
    print 1
    scheduler().enqueue_in(timedelta(seconds=5), func, arg1)
    return` 

This should print 1 every 5 seconds, but it doesn't work

**Comment by yokotoka** [comment] 2015-06-22 23:41
Yes, I have the same. Moreover, rqscheduler does nothing at all, even though I started it as in documentation (schedule periodic task & start rqscheduler or scheduler.run() ). :(

**Comment by selwin** [comment] 2015-06-23 00:53
Do you see `rqscheduler`'s startup message? If you don't, you'll probably need to tweak your logging configurations.

**Comment by Sshuichi** [comment] 2015-06-23 00:54
I don't, How do I tweak the logging conf ?

**Comment by selwin** [comment] 2015-06-23 01:02
Try this:
```python
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "rq_console": {
            "format": "%(asctime)s %(message)s",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "rq_console": {
            "level": "DEBUG",
            "class": "rq.utils.ColorizingStreamHandler",
            "formatter": "rq_console",
            "exclude": ["%(asctime)s"],
        },
    },
    'loggers': {
        "rq_scheduler.scheduler": {
            "handlers": ["rq_console"],
            "level": "DEBUG"
        },
    }
}
```

Closing this issue as this is not a bug.

**Closed by selwin** 2015-06-23 01:02 UTC
